apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-worker
  namespace: olive-dev
  labels:
    app: order-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      serviceAccountName: order-worker
      containers:
        - name: order-worker
          image: 065227443107.dkr.ecr.ap-northeast-2.amazonaws.com/olive/order-worker:dev-20260122-100451
          envFrom:
            - secretRef:
                name: aurora-cred
          env:
            - name: AWS_REGION
              value: ap-northeast-2
            - name: ORDER_QUEUE_URL
              value: "https://sqs.ap-northeast-2.amazonaws.com/065227443107/olive-dev-order-queue"
            - name: WAIT_TIME_SECONDS
              value: "20"
            - name: MAX_NUMBER_OF_MESSAGES
              value: "5"
            - name: VISIBILITY_TIMEOUT
              value: "60"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
