apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-worker
  namespace: olive-dev
  labels:
    app: order-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-worker
  template:
    metadata:
      labels:
        app: order-worker
    spec:
      serviceAccountName: order-worker
      containers:
        - name: order-worker
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              echo "[worker] started";
              while true; do
                date;
                sleep 10;
              done
          env:
            - name: AWS_REGION
              value: ap-northeast-2
            - name: ORDER_QUEUE_URL
              value: "https://sqs.ap-northeast-2.amazonaws.com/065227443107/olive-dev-order-queue"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
